# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foo.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("foo.proto", :syntax => :proto3) do
    add_message "phil_contracts.Foo" do
      optional :name, :string, 1
      optional :bar, :message, 2, "phil_contracts.Foo.Bar"
      repeated :bars, :message, 3, "phil_contracts.Foo.Bar"
      proto3_optional :number_field, :int32, 4
    end
    add_message "phil_contracts.Foo.Bar" do
      optional :name, :string, 1
    end
  end
end

module PhilContracts
  Foo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("phil_contracts.Foo").msgclass
  Foo::Bar = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("phil_contracts.Foo.Bar").msgclass
end
