name: Publish
on:
  release:
    types: [published]
jobs:
  ruby-publish:
    name: Publish Ruby Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ruby
      - name: Build gem
        working-directory: ruby
        run: >
          gem build phil_contracts.gemspec --output phil_contracts.gem
      - name: Authenticate to Github Packages
        working-directory: ruby
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
      - name: Publish gem to Github Packages
        working-directory: ruby
        run: |
          gem push --key github \
            --host https://rubygems.pkg.github.com/phil-monroe \
            phil_contracts.gem
