name: Ruby
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  ruby-tests:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.2.0'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ruby
      - name: RSpec
        working-directory: ruby
        run: >
          ./bin/rspec
