name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  ruby-tests:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.2.0'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ruby
      - name: RSpec
        working-directory: ruby
        run: >
          ./bin/rspec

  ruby-package:
    name: Publish Ruby Package
    needs: ruby-tests
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ruby
      - name: Build gem
        working-directory: ruby
        run: >
          gem build phil_contracts.gemspec --output phil_contracts.gem
      - name: Publish gem
        working-directory: ruby
        run: >
          gem push --key github \
            --host https://rubygems.pkg.github.com/phil-monroe \
            phil_contracts.gem
